### ISSUE TITLE
Is there a character limit for polls?

### ISSUE THREAD

**Issue by polleyg** [xoneco/simple-poll#24] opened 2016-07-15 05:28 UTC
Is there character limit for polls. I created a poll that had relatively long strings for the options and they show up blank (see screenshot).

Option 1 had 56 chars
Option 2 had 47 chars

![screen shot 2016-07-15 at 3 25 48 pm](https://cloud.githubusercontent.com/assets/5554342/16864511/92480fde-4aa0-11e6-896a-97124275357a.png)

I used /poll "Question?" "Option 1" "Option 2" to create it.

**Comment by wilhelmklopp** [comment] 2016-07-19 23:34
Hi, this is odd!

Just tried it again with two very long options, way past 50 characters, and it worked just fine.
So not entirely sure what is going on here. Maybe it has something to do with the content of the options?

Is there anything unusual in the option text?
Can you yourself reproduce this issue?

Really interesting 🤔

**Comment by Brobin** [comment] 2016-11-14 20:01
I think it may be due to spaces. I just created a poll with 7 options, all with spaces, and they all came up blank.

**Comment by wilhelmklopp** [comment] 2016-11-14 20:21
Hey! Do you have the exact poll slash command you used?

**Comment by Brobin** [comment] 2016-11-14 20:45
Something like this:

`/poll "What kinds of alcohol should I pick up for game night?" "White Wine" "Red Wine" "Wheat Beer" "IPA"`

**Comment by wilhelmklopp** [comment] 2016-11-14 22:41
That's a valid poll slash command.

It seems to work for me?

**Comment by Brobin** [comment] 2016-11-14 22:43
Yeah, I thought it was valid too. I had 7 options, can't remember exactly what they all were.

**Comment by jeffgore00** [comment] 2017-10-09 02:32
I believe the issue is when the closing quote is left off the poll question. i.e. /poll "What kinds of alcohol should I pick up for game night? "White
Wine" "Red Wine" "Wheat Beer" "IPA"

**Comment by wilhelmklopp** [comment] 2017-10-18 21:18
@jeffgore00 yep, that sounds about right! Thanks for confirming. I'm gonna close this for now :)

**Closed as completed by wilhelmklopp** 2017-10-18 21:18 UTC
Labels: bug
