### ISSUE TITLE
A user always answer to all options

### ISSUE THREAD

**Issue by tematim** [xoneco/simple-poll#31] opened 2016-11-04 11:05 UTC
Hello,

By default, a user have all options selected.

How is it possible to remove him, because he left the company ?

Maybe he change the source code, and add his username by default ?

Regards

**Comment by wilhelmklopp** [comment] 2016-11-05 18:00
This is a duplicate of #3 

In your case you can re-install Simple Poll or enable button polls in the dashboard: https://simplepoll.rocks/dashboard/

**Closed as completed by wilhelmklopp** 2016-11-05 18:00 UTC
