### ISSUE TITLE
Feature request: make bot react to message

### ISSUE THREAD

**Issue by harrisonlingren** [xoneco/simple-poll#22] opened 2016-06-08 21:42 UTC
I noticed that when I post a poll, it makes my account react to both messages. Is it possible to change this so that the bot reacts for each option instead so I don't have to sacrifice my vote (and also so that both options will be permanently visible)?

**Comment by wilhelmklopp** [comment] 2016-06-09 16:57
Hey,

Yes, this is a known problem :)

A fix for this is hopefully coming soon.

Duplicate of #3

**Closed as completed by wilhelmklopp** 2016-06-09 16:57 UTC
Labels: duplicate
