### ISSUE TITLE
Creator of the poll can't vote

### ISSUE THREAD

**Issue by mikeott** [xoneco/simple-poll#20] opened 2016-05-20 01:00 UTC
Unless I'm not using it properly, when I create a poll I only get the option to remove options. As the creator of the poll I should also be able to vote.

**Comment by wilhelmklopp** [comment] 2016-05-22 15:17
Hey,

Yes, this is a known problem and current constraint of the Slack API.
You should definitely be able to vote as the poll creator!

Duplicate of #3

**Closed as completed by wilhelmklopp** 2016-05-22 15:17 UTC
Labels: duplicate
