### ISSUE TITLE
Default votes

### ISSUE THREAD

**Issue by tnguyen14** [xoneco/simple-poll#5] opened 2016-01-06 19:21 UTC
When I or someone else creates a poll, all the options have 1 vote from me by default (I am the admin that installed the app). Is this the default behavior?

**Comment by wilhelmklopp** [comment] 2016-01-06 21:14
Thanks for the feedback :)

Yes, this is the default behaviour.The idea is that the emoji reactions get initialized, so that everybody else in your team can vote in a very easy and convenient manner.

The Admin not getting any votes is definitely not intended, but without the Slack API extending it's features this is the best alternative...
**I am still hopeful that this is temporary and I will change it as soon as the Slack API receives this missing feature.**

Duplicate of #3

**Closed as completed by wilhelmklopp** 2016-01-06 21:14 UTC
Labels: duplicate

**Comment by tnguyen14** [comment] 2016-01-06 21:37
I see. I saw #3 but didn't know that was the same issue. Thanks!

Could we use slackbot as the initial user?

**Comment by wilhelmklopp** [comment] 2016-01-07 17:33
So this was also something I thought about, but I couldn't find any documentation on it. It looks like it's not possible :(
If they add **this** to the API and not what is described in #3, I will probably use slackbot in the mean time.
