### ISSUE TITLE
Poll buttons are disappearing

### ISSUE THREAD

**Issue by Zhomart** [xoneco/simple-poll#32] opened 2016-11-29 16:38 UTC
When I click on buttons, they disappear. Happens to all in our team.

Here is the screenshot:

![http://i.imgur.com/2ZCfk5P.gif](http://i.imgur.com/2ZCfk5P.gif)

**Comment by wilhelmklopp** [comment] 2016-11-29 19:48
Duplicate of #3 

If you enable button polls in the dashboard settings, this problem will go away :)

https://simplepoll.rocks/dashboard/

**Closed as completed by wilhelmklopp** 2016-11-29 19:48 UTC
