### ISSUE TITLE
the user posting the poll can't poll

### ISSUE THREAD

**Issue by harryi3t** [xoneco/simple-poll#16] opened 2016-04-07 06:41 UTC
![image](https://cloud.githubusercontent.com/assets/5207331/14342749/adc6f264-fcb9-11e5-9159-8b5689da227b.png)

if I click any option button, that option is gone! for everyone!
And there is no way to add them back

What's the use of a poll without any options left?

**Comment by harryi3t** [comment] 2016-04-07 06:43
#### Here is what I meant by `the option is gone`

![anim](https://cloud.githubusercontent.com/assets/5207331/14342797/16738cd2-fcba-11e5-826d-6f496fa8425a.gif)

**Comment by wilhelmklopp** [comment] 2016-04-08 16:30
Hey,

Yes, this is a problem that I would love to fix, because there are multiple support requests each day for it, however, the Slack API doesn't really allow for any better implementation of it at this time.

You can **always** re-add the emoij reactions by adding them manually via the "Add Reaction" button, that shows up both to the left of the existing emoji or to the right of the message when you hover over it.
![Add Reaction Button](http://i.imgur.com/9reCnTJ.png)

This is a duplicate of #3

**Closed as completed by wilhelmklopp** 2016-04-08 16:30 UTC
Labels: duplicate

**Comment by Scotty79** [comment] 2016-06-16 00:06
Just created my first poll and notice all poll result buttons initially all display with 1 vote. Shouldn't they all initially display with 0 instead of 1? harryi3t's animated gif above shows all buttons immediately being populated with 1 also. Is this expected behavior?

**Comment by harryi3t** [comment] 2016-06-16 05:29
@Scotty79 yes it is.
for that icon to be there it needs atleast one vote. So the person who has added this plugin to their slack, his account will be used every time to post the vote on every option.

The way I manage this is, first let everyone vote, then I go and remove my votes from every option except the one(s) which I want to vote.

The reason is lack of permission on the command, so it cannot use itself. The author has requested the API support but has been denied.

Full description here https://www.producthunt.com/tech/simple-poll

**Comment by wilhelmklopp** [comment] 2016-06-16 12:34
@harryi3t @Scotty79 yes this is correct, with one exception: The API support has not really been denied, but it has not really been supported by Slack either.

With that said, I am confident that a fix, which will help me resolve this problem is coming in the near future :smile:

**Comment by imjoshdean** [comment] 2016-10-14 15:37
Have you considered updating this to utilize the `message-button` API in order to accomplish this? https://api.slack.com/docs/message-buttons

**Comment by wilhelmklopp** [comment] 2016-10-14 18:59
@imjoshdean replied in #26
